spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/closet?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  application:
    name: closet_back
  security:
    user:
      name: user
      password: 1234
  jpa:
    properties:
      hibernate:
        show_sql: true  # ??, ????, ??? ???? - false? ?? // SQL ?? 3? ??? ??? ??
        format_sql: true  # ??, ????, ??? ???? - false? ?? // SQL ??? ??(?? ??? ?)
        use_sql_comments: true  # ??,  ????, ??? ???? - false? ?? // ?? ??
        default_batch_fetch_size: 500
    hibernate:
      ddl-auto: create # ??, ????, ??? ????? ??? ???! - none?? ?? (ddl ?? ??)
    open-in-view: false
    show_sql: true
  redis:
    lettuce:
      pool:
      port: 6379
      host: 127.0.0.1
      password: